# Docker-compose configuration for production

version: '2'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django.production
        container_name: hooks_demo_django
        restart: unless-stopped
        volumes:
            - "/var/lib/docker-nginx/files/hooks_demo/media:/files/media"
            - "/var/lib/docker-nginx/files/hooks_demo/assets:/files/assets"
            - "/var/log/hooks_demo:/var/log/hooks_demo"
        # For some reason the command also has to be specified here, otherwise the entrypoint+command combination won't
        #  work.
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        command: gunicorn hooks_demo.wsgi:application --workers 2 --bind :80
        networks:
            - default
            - hooks_demo_nginx
            - hooks_demo_postgres
        depends_on:
            - redis
        external_links:
            - postgres-10:postgres

    node:
        build:
            context: .
            dockerfile: Dockerfile-node.production
        container_name: hooks_demo_node
        restart: unless-stopped
        command: npm run start
        volumes:
            - "/var/lib/docker-nginx/files/hooks_demo/app/assets:/files/assets"
            - "/var/log/hooks_demo:/var/log/hooks_demo"
        networks:
            - default
            - hooks_demo_nginx

    redis:
        image: redis:4.0.10-alpine
        restart: unless-stopped
        volumes:
            - "/var/lib/docker-hooks_demo/redis:/data"
        networks:
            - default

# NB: These networks must be created by fabfile and contain the global nginx/postgres containers.
# Keep it in sync with fabfile!
networks:
    default:
        external:
            name: hooks_demo_default
    hooks_demo_nginx:
        external: true
    hooks_demo_postgres:
        external: true
